### ISSUE TITLE
Consider using a problem matcher instead

### ISSUE THREAD

**Issue by ejsmith** [Tyrrrz/GitHubActionsTestLogger#1]
Just curious if you considered using a [GitHub Actions problem matcher](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md) instead of a different logger. Seems like it might be better to just have a problem matcher enabled maybe in the [dotnet GitHub Action](https://github.com/actions/setup-dotnet/blob/master/.github/csc.json) that creates problems for failing tests.

**Comment by Tyrrrz** [comment]
Yeah that would be an ideal solution. Unfortunately the output from `dotnet test` is not very structured:

```ini
X YoutubeClient_DownloadMediaStreamAsync_Test("9bZkp7q19f0") [996ms]
  Error Message:
   System.Net.Http.HttpRequestException : Response status code does not indicate success: 403 (Forbidden).
  Stack Trace:
     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Internal.HttpClientEx.GetStreamAsync(HttpClient client, String requestUri, Nullable`1 from, Nullable`1 to, Boolean ensureSuccess) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Internal\HttpClientEx.cs:line 60
   at YoutubeExplode.Internal.SegmentedHttpStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Internal\SegmentedHttpStream.cs:line 65
   at YoutubeExplode.Internal.Extensions.CopyToAsync(Stream source, Stream destination, IProgress`1 progress, CancellationToken cancellationToken, Int32 bufferSize) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Internal\Extensions.cs:line 155
   at YoutubeExplode.YoutubeClient.DownloadMediaStreamAsync(MediaStreamInfo info, Stream output, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\YoutubeClient.MediaStream.cs:line 36
   at YoutubeExplode.YoutubeClient.DownloadMediaStreamAsync(MediaStreamInfo info, String filePath, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\YoutubeClient.MediaStream.cs:line 46
   at YoutubeExplode.Tests.YoutubeClientIntegrationTests.YoutubeClient_DownloadMediaStreamAsync_Test(String videoId) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode.Tests\YoutubeClientIntegrationTests.cs:line 162
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

The only thing that signifies that this is a failed test is the `X`. Writing reliable matchers for this kind of output sounds very problematic.

Things are further complicated when we need to extract source information (file path, line number). It would be possible to include all that in a single matcher, but I imagine it's not a very fun task.

Also, this logger has a bunch of heuristics to get the source information. Ideally it should be provided by the test runner, but unfortunately it isn't. :(

https://github.com/Tyrrrz/GitHubActionsTestLogger/blob/af556380abc9dafeab21662e1f3f76e7134f7c79/GitHubActionsTestLogger/TestLogger.cs#L58-L88

**Comment by Tyrrrz** [comment]
I think the correct solution here would be to change .NET CLI so that it produces the same format of errors during test as it does during build. Then the default problem matchers in `setup-dotnet` will pick up these as errors and this project will be rendered obsolete.

**Comment by Tyrrrz** [comment]
Oh, also note that problem matchers only work on a line-by-line basis, if I understand correctly. That means it's impossible to parse the stack trace to get source information.

**Comment by ejsmith** [comment]
Agreed that it would be ideal if the same problem matcher for dotnet worked for both build errors and test failures, but not sure if that is ideal for human readable output.

The github problem matches did say that they support multi-line matches, but I haven't played with anything and I think those problem matchers come from vscode which I think you are right only supports single line.
